version: 0.2
phases:
  pre_build:
    commands:
      - yarn
      - npm install --save-dev jest
      - npm install --save-dev babel-jest regenerator-runtime
      - yarn test
  build:
   commands:
      - yarn build

reports:
    jest_reports:
        files:
            - junit.xml
        file-format: JUNITXML
        base-directory: .test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build


